import type { Metadata } from "next";
import "./globals.css";
import { DockDemo } from "@/components/Dock";
import ThemeWrapper from "@/components/ThemeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <ThemeWrapper>
          {children}
          <DockDemo />
        </ThemeWrapper>
      </body>
    </html>
  );
}
